In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Example dataset
data = np.array(["Red", "Blue", "Green", "Red", "Blue"]).reshape(-1, 1)

# Initialize OneHotEncoder
one_hot_encoder = OneHotEncoder(sparse_output=False)  # Use sparse_output=False for a dense array

# Fit and transform the data
one_hot_encoded_data = one_hot_encoder.fit_transform(data)

print(one_hot_encoded_data)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
